spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cebooklub_rewind
    username: root
    password: adminadmin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:/schema

server:
  port: 8081